### PR TITLE
Converted interview template to markdown

### PR DESCRIPTION
**Pull request by Nolski**
I was having a lot of issues getting the asciidoc format filled in properly. I went ahead and converted it to Markdown using pandoc. 

I kept the asciidoc template in there but if we have both and make changes, it'll be tough to maintain both if we're frequently making changes. I'm personally in favor of sticking with markdown as it's much simpler and more widely used. What do y'all think? We're using markdown in the wiki already.

### CODE REVIEW

**Comment by ghost** [comment]
On Mon, Jun 10, 2019 at 07:33:42AM -0700, Mike Nolan wrote:
> I was having a lot of issues getting the asciidoc format filled in properly. I
> went ahead and converted it to Markdown using pandoc.

tl;dr

Even though I didn't start down this path of using asciidoc, given that we're using it I think it would be more helpful to start with the specific complaint and work up to that larger question of whether or not to make a change, especially if that change takes us to a format with all the limitations and inconsistencies surrounding markdown.

---

Not sure what the initial impetus was for asciidoc, but if there was one it would be helpful to note it here, whatever it was.

As best I understand, reStructuredText (reST) and asciidoc both better support a more semantic approach, to the extent that reST is sufficient to feed to Sphinx for long-form document formatting in a way for which markdown is often found to be insufficient. 


For instance, I was extremely pleased to find that Gollum accepts org-mode format so that I could tractably edit tables for HFOSS. Tables are not a part of "core" markdown (if one can even speak of such a thing), but rather part of the Github-flavored markdown extensions and so less widely supported.

I would feel better if I could, for instance, move towards using asciidoc or reST and away from org-mode for nimbus of things which don't fit as comfortably in markdown. 

Some general discussion of the relative merits of various less-formal markup systems:

https://asciidoctor.org/docs/asciidoc-vs-markdown/

http://www.zverovich.net/2016/06/16/rst-vs-markdown.html

A FOSS@RIT project, a book, that used Markdown with Gitbook to produce a book-like document in spite of Markdown's limitations:

https://github.com/FOSSRIT/HowToFOSS

a call-out to an earlier iteration of the HFOSS course written in reST and rendered to Read the Docs via Sphinx:

https://hfoss.readthedocs.io/en/latest/

and this is a bit further afield, but I find to be an interesting parallel in that it also represents differences in how acceptable people approach the presence or absence of useable specs:

https://www.more-magic.net/posts/an-appeal-to-whatwg-uri-spec.html

particularly because a way to deal with markdown's deficiencies is simply to write HTML, the spec for which itself, as that link notes, has gotten rather woolly, and contentiously so.

**Comment by Nolski** [comment]
So to give some background on why aciidoc was used in the first place. I think @jwflory initially chose it just due to personal preference.

As for the specific complaint, when filling out this template, putting the answers below the questions as we are taking notes during the intro calls, causes issues with the formatting (most notably removing the number formatting.) The existing knowledge of how asciidoc formatting works is fairly minimal. 

When we were initially discussing out wiki format in our matrix chat room `#rit-librecorps:matrix.org` we decided that it seemed best to start with markdown and github wiki as it's the simplest to get started with. I think our documentation has so far been simple enough that the features markdown provides (without having to write html) have been plenty powerful enough for us to use thus far. 

Our wiki and all other documentation has been written in markdown except this one document so I think it would be fair to say that we started using markdown and switched to asciidoc for this one file.

**Comment by justwheel** [comment]
> So to give some background on why aciidoc was used in the first place. I think @jwflory initially chose it just due to personal preference.

This is 100% the background and motivation. No need to debate this. Markdown is more commonly understood and used, let's use what people know. :smile: 

@Nolski I do have one request though. Could we pretty please use the [One Sentence Per Line](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line) convention? This is most helpful for reviewing diffs in pull requests. It also makes it easier to swap order of sentences round as needed (e.g. copy+pasting a line in a different order) and it can be a helpful writing awareness technique to write shorter, more concise sentences.

It's not required, but this is a convention I've fallen in love with and I think is easier than using fixed character limits per line. What do you think?

**Comment by Nolski** [comment]
Hey @jwflory thanks for the suggestion and explanation! I've never heard of that convention but I really dig it. My latest commit updates the file to use that convention as well as a couple of other style updates. I've reformatted the [Gates Foundation cohort wikis](https://github.com/FOSSRIT/librecorps/wiki/Macro-Eyes#intro-call) to use that template and it seems to work out really well and is easy to fill out inline.

What do you think?

**Review by justwheel — APPROVED** [review]
Looks great to me! :sunglasses: I think this is ready to merge. :clapper:

**Pull request merged**
